### ISSUE TITLE
About Open Source the Dialogue Simulator

### ISSUE THREAD

**Issue by JACKHAHA363** [google-research-datasets/simulated-dialogue#4]
Thanks for sharing the dataset, but is it also possible to open source the code for the dialogue simulator with the sentence templates?

**Comment by abhirast** [comment]
The code uses some google-internal libraries. Open sourcing the code requires some refactoring to create a standalone version and also some IP approvals. Unfortunately it is not possible to do it soon since most of the authors are no longer working on this project. I am closing this issue but please feel free to reach out to the authors with questions.
